# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under domain_mlops/resources/*
# and domain_mlops/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for domain_mlops Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./domain_mlops

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: domain_mlops-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t domain_staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t domain_staging
